name: action-tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test_defaults:
    runs-on: ubuntu-latest
    name: Test local action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Environment
        run: |
          bash -c set

      - name: Get token local action
        id: get_token
        uses: ./  # Uses an action in the root directory
        with:
          APP_ID: ${{ vars.VCT_GHT_APP_ID }}
          APP_PEM: ${{ secrets.VCT_GHT_APP_PEM }}

      - name: Check App Installation Token
        run: |
          echo "This token is masked: ${TOKEN}"
        env:
          TOKEN: ${{ steps.get_token.outputs.app_token }}
